# Generated by Django 2.2.13 on 2020-07-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200715_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item2',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='addresses',
            new_name='address',
        ),
    ]
