# Generated by Django 2.2.13 on 2020-08-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20200719_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
